/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/VoiceServices.framework/VoiceServices
 */

#import "VoiceServices-Structs.h"
#import <Foundation/NSArray.h>


@interface NSArray (VSRecognitionSessionKeywords)
-(id)_nextKeywordUsingCursors:(CFDictionaryRef)cursors;
-(id)_scrambledKeywordsAndAddToSet:(id)set;
@end

