/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/VoiceServices.framework/VoiceServices
 */

#import <Foundation/NSObject.h>

@class NSString;

@interface VSCacheUpdateRequest : NSObject {
	NSString *_modelID;
	NSString *_classID;
}
-(id)initWithModelIdentifier:(id)modelIdentifier classIdentifier:(id)identifier;
-(id)classIdentifier;
-(id)coalescedRequest:(id)request;
-(void)dealloc;
-(id)description;
-(id)modelIdentifier;
@end

