/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/VoiceServices.framework/VoiceServices
 */

#import <Foundation/NSObject.h>

@class NSLock, NSMutableArray, NSDictionary, NSTimer;

@interface VSCacheUpdateListener : NSObject {
	NSLock *_lock;
	NSMutableArray *_updateRequestQueue;
	NSDictionary *_dataProviders;
	NSTimer *_flushTimer;
	BOOL _isListening;
}
+(id)sharedListener;
+(id)sharedListenerIfExists;
-(id)init;
-(void)_enqueueRequest:(id)request;
-(void)_flush;
-(id)_initShared;
-(void)_spokenLanguageChanged:(id)changed;
-(void)dealloc;
-(void)performUpdateForModelIdentifier:(id)modelIdentifier classIdentifier:(id)identifier;
-(void)startListening;
-(void)stopListening;
@end

