/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/VoiceServices.framework/VoiceServices
 */

#import <Foundation/NSObject.h>

@class NSDictionary, NSString;

@interface VSFormatArgument : NSObject {
	NSString *formatSpecifier;
	NSDictionary *attributes;
	NSString *formattedArg;
}
-(void)dealloc;
@end

