/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/VoiceServices.framework/VoiceServices
 */

#import <Foundation/NSObject.h>
#import "VSGenericUpdate.h"


@interface VSGenericBlockHolder : NSObject <VSGenericUpdate> {
@private
	id _block;
}
-(id)initWithBlock:(id)block;
//-(void).cxx_destruct;
-(void)invokeUpdateWithObject:(id)object;
@end
