/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/VoiceServices.framework/VoiceServices
 */

#import "VoiceServices-Structs.h"
#import "VSRecognitionAction.h"

@class NSAttributedString, NSString, NSArray;

@interface VSRecognitionRecognizeAction : VSRecognitionAction {
	NSString *_modelIdentifier;
	NSArray *_keywords;
	void *_recognition;
	NSArray *_results;
	NSString *_debugDumpPath;
	NSString *_audioInputPath;
	double _levelInterval;
	struct {
		unsigned debugDumpEnabled : 1;
		unsigned preferredEngine : 2;
		unsigned resetEngine : 1;
		unsigned bluetoothAllowed : 1;
		unsigned hasStarted : 1;
	} _recognizeFlags;
}
-(id)initWithModelIdentifier:(id)modelIdentifier;
-(id)_actionForEmptyResults;
-(void)_configureNewRecognitionInstance;
-(void)_continueAfterDeferredStart;
-(VSRecognitionRef)_createRecognitionInstanceWithCallbacks:(XXStruct__Vsh7C *)callbacks info:(void *)info;
-(id)_debugDumpPath;
-(void)_handleRecognitionCompleted:(VSRecognitionRef)completed withResults:(CFArrayRef)results error:(CFErrorRef)error;
-(void)_handleRecognitionPrepared:(VSRecognitionRef)prepared;
-(void)_handleRecognitionStarted:(VSRecognitionRef)started;
-(void)_handledThreadedResults:(id)results nextAction:(id)action;
-(BOOL)_hasDeferredStartCallback;
-(float)_inputLevel;
-(float)_inputLevelDB;
-(BOOL)_isActivelyRecognizing;
-(BOOL)_isRecognizing;
-(id)_keywordAtIndex:(int)index;
-(int)_keywordCount;
-(BOOL)_keywordIndexChanged;
-(id)_keywords;
-(void)_releaseFromPrepare;
-(void)_reset;
-(BOOL)_setAudioInputPath:(id)path;
-(BOOL)_setBluetoothInputAllowed:(BOOL)allowed;
-(BOOL)_setDebugDumpEnabled:(BOOL)enabled;
-(BOOL)_setDebugDumpEnabled:(BOOL)enabled dumpPath:(id)path;
-(BOOL)_setDebugDumpPath:(id)path;
-(BOOL)_setEngineResetRequired:(BOOL)required;
-(BOOL)_setInputLevelUpdateInterval:(double)interval;
-(BOOL)_setPreferredEngine:(int)engine;
-(void)_setResults:(id)results;
-(id)cancel;
-(int)completionType;
-(void)dealloc;
-(id)modelIdentifier;
-(id)perform;
@end
