/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/VoiceServices.framework/VoiceServices
 */

#import "VSRecognitionAction.h"

@class NSAttributedString, NSString, NSURL;

@interface VSRecognitionURLAction : VSRecognitionAction {
	NSURL *_url;
}
-(id)URL;
-(int)completionType;
-(void)dealloc;
-(id)perform;
-(void)setURL:(id)url;
@end

