/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/VoiceServices.framework/VoiceServices
 */

#import <Foundation/NSObject.h>

@class NSString, VSRecognitionSession, NSAttributedString;

@interface VSRecognitionAction : NSObject {
@private
	NSString *_resultString;
	NSString *_statusString;
	union {
		NSString *stringValue;
		NSAttributedString *attributedStringValue;
	} _spokenString;
	VSRecognitionSession *_session;
	unsigned _spokenStringIsAttributed : 1;
}
-(void)_continueAfterDeferredStart;
-(BOOL)_hasDeferredStartCallback;
-(id)_session;
-(void)_setSession:(id)session;
-(id)cancel;
-(void)completeWithNextAction:(id)nextAction error:(id)error;
-(int)completionType;
-(void)dealloc;
-(id)perform;
-(id)resultDisplayString;
-(BOOL)sensitiveActionsEnabled;
-(void)setResultDisplayString:(id)string;
-(void)setSpokenFeedbackAttributedString:(id)string;
-(void)setSpokenFeedbackString:(id)string;
-(void)setStatusDisplayString:(id)string;
-(id)spokenFeedbackAttributedString;
-(id)spokenFeedbackString;
-(id)statusDisplayString;
@end

