/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/VoiceServices.framework/VoiceServices
 */

#import "VSRecognitionRecognizeAction.h"

@class NSAttributedString, NSString;

@interface VSRecognitionConfirmAction : VSRecognitionRecognizeAction {
	VSRecognitionAction *_confirmedAction;
	VSRecognitionAction *_deniedAction;
	struct {
		unsigned initializing : 1;
		unsigned confirmed : 1;
	} _confirmFlags;
}
-(id)init;
-(id)initWithModelIdentifier:(id)modelIdentifier;
-(void)_setConfirmed:(BOOL)confirmed;
-(int)completionType;
-(id)confirmedAction;
-(void)dealloc;
-(id)deniedAction;
-(void)setConfirmedAction:(id)action;
-(void)setDeniedAction:(id)action;
@end

