/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/VoiceServices.framework/VoiceServices
 */

#import <Foundation/NSObject.h>


@interface VSRecognitionResult : NSObject {
}
+(void)initialize;
+(id)recognitionResultWithModelIdentifier:(id)modelIdentifier classIdentifiers:(id)identifiers values:(id)values;
-(id)init;
-(id)createHandler;
-(id)description;
-(int)elementCount;
-(BOOL)getElementClassIdentifier:(id *)identifier value:(id *)value atIndex:(int)index;
-(unsigned)hash;
-(BOOL)isEqual:(id)equal;
-(id)modelIdentifier;
-(id)recognitionAction;
-(id)recognitionResultByReplacingValueForClassIdentifier:(id)classIdentifier withValue:(id)value;
-(oneway void)release;
-(id)retain;
-(unsigned)retainCount;
-(void)setRecognitionAction:(id)action;
-(id)valueOfFirstElementWithClassIdentifier:(id)classIdentifier;
@end

