/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/VoiceServices.framework/VoiceServices
 */

#import <Foundation/NSObject.h>

@class NSMutableArray, NSConditionLock;
@protocol VSRecognitionResultHandlingThreadDelegate;

@interface VSRecognitionResultHandlingThread : NSObject {
	id<VSRecognitionResultHandlingThreadDelegate> _delegate;
	NSMutableArray *_requests;
	NSConditionLock *_lock;
	struct {
		unsigned running : 1;
		unsigned delegateDidHandleResults : 1;
		unsigned valid : 1;
	} _resultHandlingFlags;
}
-(id)init;
-(void)_handleRequests;
-(void)_notifyRequestHandled:(id)handled;
-(void)dealloc;
-(void)handleResults:(id)results withHandler:(id)handler;
-(void)invalidate;
-(void)setDelegate:(id)delegate;
@end

