/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/VoiceServices.framework/VoiceServices
 */

#import "VSSpeechServiceDelegate.h"
#import "VoiceServices-Structs.h"
#import <Foundation/NSObject.h>

@class VSSpeechConnection, VSSpeechRequest;
@protocol VSSpeechConnectionDelegate;

@interface VSSpeechConnectionDelegateWrapper : NSObject <VSSpeechServiceDelegate> {
@private
	id<VSSpeechConnectionDelegate> _delegate;
	VSSpeechRequest *_request;
	VSSpeechConnection *_connection;
}
@property(assign, nonatomic) __weak VSSpeechConnection *connection;	// @synthesize=_connection
@property(assign, nonatomic) __weak id<VSSpeechConnectionDelegate> delegate;	// @synthesize=_delegate
@property(retain, nonatomic) VSSpeechRequest *request;	// @synthesize=_request
//-(void).cxx_destruct;
// declared property getter: -(id)connection;
// declared property getter: -(id)delegate;
// declared property getter: -(id)request;
// declared property setter: -(void)setConnection:(id)connection;
// declared property setter: -(void)setDelegate:(id)delegate;
// declared property setter: -(void)setRequest:(id)request;
-(oneway void)speechRequestDidContinue;
-(oneway void)speechRequestDidPause;
-(oneway void)speechRequestDidStart;
-(oneway void)speechRequestDidStopWithSuccess:(BOOL)speechRequest phonemesSpoken:(id)spoken error:(id)error;
-(oneway void)speechRequestMark:(int)mark didStartForRange:(NSRange)range;
@end
