/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/VoiceServices.framework/VoiceServices
 */

#import "VoiceServices-Structs.h"
#import <Foundation/NSObject.h>

@class NSString, NSArray;

@interface VSTextPreProcessor : NSObject {
	NSArray *_rules;
	NSString *_languageID;
	CFStringTokenizerRef _tokenizer;
}
-(id)initWithContentsOfPath:(id)path languageIdentifier:(id)identifier;
-(void)dealloc;
-(id)processedTextFromString:(id)string;
@end

