/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/VoiceServices.framework/VoiceServices
 */

#import <Foundation/NSObject.h>
#import "VoiceServices-Structs.h"

@class NSString;

@interface VSTextPreProcessorRule : NSObject {
	NSString *_matchPattern;
	NSString *_replacement;
	BOOL _caseSensitive;
	BOOL _eatPunctuation;
}
-(id)initWithDictionaryRepresentation:(id)dictionaryRepresentation;
-(void)dealloc;
-(id)matchedString:(id)string forTokenInRange:(XXStruct_K5nmsA *)range;
@end

