/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/VoiceServices.framework/VoiceServices
 */

#import <Foundation/Foundation.h>

@class NSString, NSArray;

@interface VSVoiceAsset : NSObject <NSSecureCoding> {
@private
	BOOL _isInstalled;
	BOOL _isBuiltInVoice;
	NSString *_name;
	NSArray *_languages;
	int _gender;
	int _footprint;
}
@property(readonly, assign, nonatomic) int footprint;	// @synthesize=_footprint
@property(readonly, assign, nonatomic) int gender;	// @synthesize=_gender
@property(assign, nonatomic) BOOL isBuiltInVoice;	// @synthesize=_isBuiltInVoice
@property(readonly, assign, nonatomic) BOOL isInstalled;	// @synthesize=_isInstalled
@property(readonly, assign, nonatomic) NSArray *languages;	// @synthesize=_languages
@property(readonly, assign, nonatomic) NSString *name;	// @synthesize=_name
+(BOOL)supportsSecureCoding;
-(id)initWithCoder:(id)coder;
-(id)initWithDictionaryRepresentation:(id)dictionaryRepresentation;
-(id)initWithName:(id)name languages:(id)languages gender:(int)gender footprint:(int)footprint isInstalled:(BOOL)installed;
//-(void).cxx_destruct;
-(id)description;
-(id)dictionaryRepresentation;
-(void)encodeWithCoder:(id)coder;
// declared property getter: -(int)footprint;
// declared property getter: -(int)gender;
// declared property getter: -(BOOL)isBuiltInVoice;
// declared property getter: -(BOOL)isInstalled;
// declared property getter: -(id)languages;
// declared property getter: -(id)name;
// declared property setter: -(void)setIsBuiltInVoice:(BOOL)voice;
@end
