/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 7, 2014, 2:26:45 AM Eastern European Standard Time
* Operating System: Version 6.1.6 (Build 10B500)
* Image Source: /System/Library/PrivateFrameworks/VoiceServices.framework/VoiceServices
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class NSString, NSAttributedString;

//typedef struct __CFDictionary* CFDictionaryRef;

typedef union {
	NSString* stringValue;
	NSAttributedString* attributedStringValue;
} SCD_Union_VS1;

typedef struct __VSRecognitionDisambiguationContext* VSRecognitionDisambiguationContextRef;

typedef struct __VSRecognition* VSRecognitionRef;

typedef struct {
	/*function pointer*/void* field1;
	/*function pointer*/void* field2;
	/*function pointer*/void* field3;
} SCD_Struct_VS4;

//typedef struct __CFArray* CFArrayRef;

//typedef struct __CFError* CFErrorRef;

typedef struct __VSSpeech* VSSpeechRef;

//typedef struct __CFString* CFStringRef;

typedef struct {
	int field1;
	int field2;
} SCD_Struct_VS9;

typedef struct __CFStringTokenizer* CFStringTokenizerRef;
