/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 7, 2014, 2:26:44 AM Eastern European Standard Time
* Operating System: Version 6.1.6 (Build 10B500)
* Image Source: /System/Library/PrivateFrameworks/VoiceServices.framework/VoiceServices
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/
#import "VoiceServices-Structs.h"

@class NSString, VSRecognitionSession;

@interface VSRecognitionAction : NSObject {

	NSString* _resultString;
	NSString* _statusString;
	SCD_Union_VS1 _spokenString;
	VSRecognitionSession* _session;
	unsigned _spokenStringIsAttributed : 1;

}
-(void)dealloc;
-(id)cancel;
-(id)perform;
-(void)_continueAfterDeferredStart;
-(char)_hasDeferredStartCallback;
-(int)completionType;
-(void)_setSession:(id)arg1 ;
-(id)spokenFeedbackString;
-(id)spokenFeedbackAttributedString;
-(id)resultDisplayString;
-(id)statusDisplayString;
-(char)sensitiveActionsEnabled;
-(id)_session;
-(void)setResultDisplayString:(id)arg1 ;
-(void)setStatusDisplayString:(id)arg1 ;
-(void)setSpokenFeedbackString:(id)arg1 ;
-(void)setSpokenFeedbackAttributedString:(id)arg1 ;
-(void)completeWithNextAction:(id)arg1 error:(id)arg2 ;
@end
