@class NSHashTable, UIImage;

@interface SBIcon : NSObject {
	NSHashTable* _observers;
	id _badgeNumberOrString;
	unsigned _uninstalled : 1;
	UIImage* _cachedIconImages[12];
}
@property(readonly, assign, nonatomic) BOOL shouldWarmUp;
+(id)memoryMappedIconImageOfSize:(CGSize)size scale:(float)scale withDrawing:(id)drawing;
+(id)memoryMappedIconImageForIconImage:(id)iconImage;
+(id)_iconImageOfSize:(CGSize)size scale:(float)scale failGracefully:(BOOL)gracefully drawing:(id)drawing;
-(id)folderFallbackTitle;
-(id)folderTitleOptions;
-(id)uninstallAlertCancelTitle;
-(id)uninstallAlertConfirmTitle;
-(id)uninstallAlertBodyForAppWithDocumentUpdatesPending;
-(id)uninstallAlertBodyForAppWithDocumentsInCloud;
-(id)uninstallAlertBody;
-(id)uninstallAlertTitleForAppWithDocumentUpdatesPending;
-(id)uninstallAlertTitleForAppWithDocumentsInCloud;
-(id)uninstallAlertTitle;
-(BOOL)isUninstalled;
-(void)setUninstalled;
-(void)completeUninstall;
-(BOOL)allowsUninstall;
-(void)launchFromViewSwitcher;
-(void)launch;
-(id)automationID;
-(void)setBadge:(id)badge;
-(void)noteBadgeDidChange;
-(int)accessoryTypeForLocation:(int)location;
-(id)badgeTextForLocation:(int)location;
-(id)badgeNumberOrString;
-(int)badgeValue;
-(void)reloadIconImagePurgingImageCache:(BOOL)cache;
-(void)reloadIconImage;
-(void)purgeCachedImages;
-(id)gridCellImage;
-(id)getGenericIconImage:(int)image;
-(id)getIconImage:(int)image;
-(id)getStandardIconImageForLocation:(int)location;
-(BOOL)shouldCacheImageForFormat:(int)format;
-(id)generateIconImage:(int)image;
-(BOOL)launchEnabled;
-(id)tags;
-(BOOL)matchesEntity:(id)entity;
-(int)localizedCompareDisplayNames:(id)names;
-(BOOL)canEllipsizeLabel;
-(id)displayName;
-(void)localeChanged;
-(BOOL)matchesRepresentation:(id)representation;
-(id)representation;
-(void)dealloc;
-(id)init;
-(id)iconOverlayImageForLocation:(int)location;
-(int)iconFormatForLocation:(int)location;
-(BOOL)hasCachedImageForLocation:(int)location;
-(id)nodeDescriptionWithPrefix:(id)prefix;
-(void)removeNodeObserver:(id)observer;
-(void)addNodeObserver:(id)observer;
-(id)nodesAlongIndexPath:(id)path consumedIndexes:(unsigned)indexes;
-(id)indexPathsForContainedNodeIdentifier:(id)containedNodeIdentifier prefixPath:(id)path;
-(id)containedNodeIdentifiers;
-(BOOL)containsNodeIdentifier:(id)identifier;
-(id)nodeIdentifier;
-(BOOL)hasObserver:(id)observer;
-(void)removeObserver:(id)observer;
-(void)addObserver:(id)observer;
-(id)application;
-(BOOL)isApplicationIcon;
-(BOOL)isBookmarkIcon;
-(id)download;
-(BOOL)isDownloadingIcon;
-(BOOL)isUserInstalledApplicationIcon;
-(BOOL)isWebApplicationIcon;
-(id)folder;
-(BOOL)isFolderIcon;
-(id)applicationBundleID;
-(id)webClip;
-(id)leafIdentifier;
-(BOOL)isLeafIcon;
-(BOOL)isPrintStatusIcon;
-(void)_notifyLaunchEnabledDidChange;
-(void)_notifyAccessoriesDidUpdate;
-(void)_notifyImageDidUpdate;
-(BOOL)iconAppearsInNewsstand;
-(BOOL)isNewsstandApplicationIcon;
-(BOOL)isNewsstandIcon;
-(BOOL)isEmptyPlaceholder;
-(BOOL)isGrabbedIconPlaceholder;
-(BOOL)isPlaceholder;
@end
